### PR TITLE
Counting Dispatched Messages

### PR DESCRIPTION
**Pull request by TarsisioXavier**
# The Problem
Sometimes, we only want to make sure some message wasen't dispatched, or we lack of some fields that are created in the code execution, but we only want to make sure that we got something dispatched or not.

# The Solution
Here's two simple assertions that can do that simply by counting the messages dispatched in the code execution.

# Testing
- Add this package to some project.
- Create a test where some or none messages it's being dispatched.
- Make you assertions using the new functions.

### CODE REVIEW

**Comment by jleonardolemos** [comment]
@TarsisioXavier The pipeline has failed

**Comment by TarsisioXavier** [comment]
@jleonardolemos I've added the actions on my repo. It's saying that the pipeline is now passing :)

**Comment by TarsisioXavier** [comment]
Any plans on merging this one? 🤔

**Comment by jleonardolemos** [comment]
> Any plans on merging this one? thinking
I'll take a look!

**Comment by jleonardolemos** [comment]
@TarsisioXavier i have the intention to merge this MR in 2.2 that will support PHP 8.2 and L10. What about add some documentation in "Testing > Asserting" after the "Consumming" session??

**Comment by TarsisioXavier** [comment]
@jleonardolemos ok, I've added the usage of the functions.

**Pull request merged**
